export const DUMMY_PRODUCTS = [
  {
    id: 'u1',
    name: 'Funko Pop Daenerys',
    avatar: 'product-1.jpg',
    description: 'Esse funko é da serie The walking dead da personagem danerys',
    price: "10.12",
    onsale: true,
  },
  {
    id: 'u2',
    name: 'Emily Thompson',
    avatar: 'product-2.jpg',
    description: 'teste1',
    price: "34.12",
    onsale: false,
  },
  {
    id: 'u3',
    name: 'Marcus Johnson',
    avatar: 'product-3.jpg',
    description: 'teste1',
    price: "34.12",
    onsale: false,
  },
  {
    id: 'u4',
    name: 'David Miller',
    avatar: 'product-4.jpg',
    description: 'teste1',
    price: "34.12",
    onsale: false,
  },
  {
    id: 'u5',
    name: 'Priya Patel',
    avatar: 'product-5.jpg',
    description: 'teste1',
    price: "34.12",
    onsale: false,
  },
  {
    id: 'u6',
    name: 'Arjun Singh',
    avatar: 'product-6.jpg',
    description: 'teste1',
    price: "34.12",
    onsale: false,
  },
];
