export const DUMMY_PRODUCTS = [
  {
    id: 'u1',
    name: 'Superman',
    avatar: 'pop-1.png',
    description: 'O Funko Pop! O Superman Funko Pop traz o icônico herói da DC Comics em uma versão estilizada e colecionável, com todos os detalhes que tornam esse herói único. Vestindo seu clássico traje azul com o famoso “S” no peito, capa vermelha e expressão confiante, este Funko Pop é perfeito para qualquer fã do Homem de Aço. Com sua característica cabeça grande e olhos expressivos, ele se destaca como uma peça indispensável para os colecionadores e admiradores do Superman. Ideal para decorar sua estante ou para dar aquele toque especial ao seu espaço geek, o Funko Pop Superman é uma verdadeira homenagem a esse ícone dos quadrinhos e do cinema.',
    price: "132.50",
    onsale: true,
  },
  {
    id: 'u2',
    name: 'Daenerys Targaryen',
    avatar: 'pop-2.png',
    description: 'O Funko Pop! A Daenerys Targaryen Funko Pop traz à vida a poderosa e implacável Mãe dos Dragões, uma das personagens mais icônicas de "Game of Thrones". Com seus cabelos platinados e seu traje real, ela aparece com a confiança e a determinação que a tornaram uma líder imbatível. Com detalhes impressionantes, incluindo a silhueta de seus dragões, Drogon, Rhaegal e Viserion, e seu olhar decidido, este Funko Pop captura perfeitamente o espírito da Daenerys em sua jornada épica. Seja para os fãs da série ou colecionadores, o Funko Pop Daenerys Targaryen é uma peça indispensável para quem acompanha sua ascensão ao trono de ferro e a dominação do continente.',
    price: "320.25",
    onsale: false,
  },
  {
    id: 'u3',
    name: 'Hulk',
    avatar: 'pop-3.png',
    description: 'O Funko Pop! Hulk traz à vida o incrível gigante verde da Marvel, conhecido por sua força incomparável e sua personalidade explosiva. Com sua pele verde vibrante, músculos gigantes e uma expressão feroz, este Funko Pop captura toda a essência do herói. Vestindo suas calças rasgadas e com os punhos cerrados, prontos para a ação, ele é a verdadeira representação do Hulk em sua forma mais icônica. Ideal para colecionadores e fãs dos Vingadores, o Funko Pop Hulk é uma peça essencial para adicionar à sua coleção de heróis da Marvel e mostrar toda a força desse personagem lendário.',
    price: "345.50",
    onsale: false,
  },
  {
    id: 'u4',
    name: 'Eleven',
    avatar: 'pop-4.png',
    description: 'O Funko Pop! Eleven traz à vida uma das personagens mais amadas de Stranger Things, a misteriosa e poderosa Eleven. Com seu visual icônico, incluindo o vestido rosa, casaco verde e tênis, este Funko Pop captura a essência da garota que possui habilidades extraordinárias. Seu olhar determinado e a expressão serena refletem sua jornada única e seu crescimento ao longo da série. Perfeito para os fãs de Stranger Things, o Funko Pop Eleven é uma peça essencial para qualquer colecionador e uma verdadeira homenagem à personagem que cativou o mundo com sua força, coragem e empatia.',
    price: "500",
    onsale: false,
  },
  {
    id: 'u5',
    name: 'Luna Lovegood',
    avatar: 'pop-5.png',
    description: 'O Funko Pop! A Luna Lovegood Funko Pop é a representação perfeita da excêntrica e encantadora personagem de "Harry Potter". Com seus óculos radiais e um sorriso sonhador, Luna traz todo o seu estilo único e personalidade irreverente para essa figura colecionável. Usando seu traje de Hogwarts, com a gravata e a capa da Grifinória, essa versão do Funko Pop captura a essência da personagem — uma mistura de inteligência, gentileza e uma visão de mundo totalmente própria. Ideal para os fãs da série, o Funko Pop Luna Lovegood é uma peça essencial para quem adora a magia e os mistérios do universo bruxo.',
    price: "225",
    onsale: false,
  },
  {
    id: 'u6',
    name: 'Alastor Moody',
    avatar: 'pop-6.png',
    description: 'O Funko Pop! Alastor Moody traz à vida o excêntrico e enigmático auror de Harry Potter, conhecido como "Olho-Tonto". Com seu olho mágico e a cicatriz no rosto, ele é retratado em sua versão mais imponente, usando seu traje de auror e com um semblante sério e vigilante. A figura captura perfeitamente sua natureza desconfiada e alerta, refletindo a personalidade única de Moody, que sempre se mantém em guarda, pronto para enfrentar qualquer ameaça. Ideal para os fãs da série, o Funko Pop Alastor Moody é uma peça indispensável para quem adora o universo de Harry Potter e a misteriosa figura desse lendário auror.',
    price: "90.50",
    onsale: true,
  },
];
